In [1]:
import pandas as pd
import datetime as datetime
import matplotlib.pyplot as plt

df = pd.read_csv('hourly_pm2.5_data.csv')

In [2]:
df

,Unnamed: 0,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,...,detection_limit,uncertainty,qualifier,method_type,method,method_code,state,county,date_of_last_change,cbsa_code
0,0,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FRM,R & P Model 2025 PM2.5 Sequential w/WINS - GRA...,118,Utah,Salt Lake,NaN,41620
1,1,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FRM,R & P Model 2025 PM2.5 Sequential w/WINS - GRA...,118,Utah,Salt Lake,NaN,41620
2,2,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FRM,R & P Model 2025 PM2.5 Sequential w/WINS - GRA...,118,Utah,Salt Lake,NaN,41620
3,3,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FRM,R & P Model 2025 PM2.5 Sequential w/WINS - GRA...,118,Utah,Salt Lake,NaN,41620
4,4,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FRM,R & P Model 2025 PM2.5 Sequential w/WINS - GRA...,118,Utah,Salt Lake,NaN,41620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220442,220442,49,35,3006,88101,2,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FEM,Thermo Scientific Model 5030 SHARP w/VSCC - Be...,184,Utah,Salt Lake,2026-08-11,41620
220443,220443,49,35,3006,88101,2,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FEM,Thermo Scientific Model 5030 SHARP w/VSCC - Be...,184,Utah,Salt Lake,2026-08-11,41620
220444,220444,49,35,3006,88101,2,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FEM,Thermo Scientific Model 5030 SHARP w/VSCC - Be...,184,Utah,Salt Lake,2026-08-11,41620
220445,220445,49,35,3006,88101,2,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FEM,Thermo Scientific Model 5030 SHARP w/VSCC - Be...,184,Utah,Salt Lake,2026-08-11,41620
220446,220446,49,35,3006,88101,2,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,2.0,NaN,NaN,FEM,Thermo Scientific Model 5030 SHARP w/VSCC - Be...,184,Utah,Salt Lake,2026-08-11,41620

In [3]:
#merge the data and the time columns
df["date_time_merged"] = df["date_local"] + ' ' + df["time_local"]
#create a proper datetime column
df["date_time"] = pd.to_datetime(df["date_time_merged"])

In [4]:
df["years"] = df["date_time"].dt.year
df["days"] = df["date_time"].dt.day
df["hours"] = df['date_time'].dt.hour
df["day of week"] = df['date_time'].dt.day_of_week
df["day of year"] = df['date_time'].dt.day_of_year

In [5]:
df["day of week"]

0         4
1         5
2         6
3         0
4         1
         ..
220442    4
220443    4
220444    4
220445    4
220446    4
Name: day of week, Length: 220447, dtype: int32

In [9]:
df_by_day = df[df["sample_duration"] == "24 HOUR"]
df_by_day

,Unnamed: 0,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,...,county,date_of_last_change,cbsa_code,date_time_merged,date_time,years,days,hours,day of week,day of year
0,0,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,NaN,41620,1999-01-01 00:00,1999-01-01,1999,1,0,4,1
1,1,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,NaN,41620,1999-01-02 00:00,1999-01-02,1999,2,0,5,2
2,2,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,NaN,41620,1999-01-03 00:00,1999-01-03,1999,3,0,6,3
3,3,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,NaN,41620,1999-01-04 00:00,1999-01-04,1999,4,0,0,4
4,4,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,NaN,41620,1999-01-05 00:00,1999-01-05,1999,5,0,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210266,210266,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,2026-08-12,41620,2026-07-27 00:00,2026-07-27,2026,27,0,0,208
210267,210267,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,2026-08-12,41620,2026-07-28 00:00,2026-07-28,2026,28,0,1,209
210268,210268,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,2026-08-12,41620,2026-07-29 00:00,2026-07-29,2026,29,0,2,210
210269,210269,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,2026-08-12,41620,2026-07-30 00:00,2026-07-30,2026,30,0,3,211
210270,210270,49,35,3006,88101,1,40.736389,-111.872222,WGS84,PM2.5 - Local Conditions,...,Salt Lake,2026-08-12,41620,2026-07-31 00:00,2026-07-31,2026,31,0,4,212

In [10]:
df.plot(df_by_day["days"], df_by_day["sample_measurement"])
plt.show()

KeyError: "None of [Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,\n       ...\n       22, 23, 24, 25, 26, 27, 28, 29, 30, 31],\n      dtype='int32', length=10055)] are in the [columns]"

In [ ]:
df.drop